/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasPenggantiLibur;

import javax.swing.JOptionPane;

/**
 *
 * @author akels
 */
public class AnekaTravel extends javax.swing.JFrame {

    /**
     * Creates new form AnekaTravel
     */
    public AnekaTravel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgKelas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbEkonomi = new javax.swing.JRadioButton();
        rbExecutive = new javax.swing.JRadioButton();
        rbSe = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtTiket = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtPajak = new javax.swing.JTextField();
        txtTBayar = new javax.swing.JTextField();
        txtPembayaran = new javax.swing.JTextField();
        txtKembalian = new javax.swing.JTextField();
        cbTujuan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PT. TRAVEL ANEKA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tujuan");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kelas");

        rgKelas.add(rbEkonomi);
        rbEkonomi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbEkonomi.setText("Ekonomi");
        rbEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEkonomiActionPerformed(evt);
            }
        });

        rgKelas.add(rbExecutive);
        rbExecutive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbExecutive.setText("Executive");
        rbExecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbExecutiveActionPerformed(evt);
            }
        });

        rgKelas.add(rbSe);
        rbSe.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbSe.setText("Super Executive");
        rbSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah Tiket");

        txtTiket.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiketActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Informasi Tiket");

        btnProses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tujuan");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Kelas");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Harga Per Tiket");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Total");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Pajak 10%");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Total Bayar");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Pembayaran");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Uang Pembayaran");

        btnBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Uang Kembalian");

        txtTujuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTujuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtKelas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtHarga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPajak.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPajak.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtTBayar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTBayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPembayaran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtKembalian.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtKembalian.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbTujuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tujuan", "Bukittinggi", "Solok", "Batusangkar", "Sijunjung", "Padang Panjang" }));
        cbTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTujuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rbEkonomi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                            .addComponent(txtTiket, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                        .addGap(44, 44, 44)
                                        .addComponent(rbExecutive)
                                        .addGap(70, 70, 70)
                                        .addComponent(rbSe))
                                    .addComponent(cbTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPajak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTujuan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTBayar)))
                            .addComponent(btnProses, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(198, 198, 198))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(217, 217, 217))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(380, 380, 380))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(235, 235, 235))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbEkonomi)
                            .addComponent(rbExecutive)
                            .addComponent(rbSe)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(txtTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBayar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(724, 819));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiketActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        if (!rbEkonomi.isSelected() && !rbExecutive.isSelected() && !rbSe.isSelected()) {
            JOptionPane.showMessageDialog(this, "Tujuan belum dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                int nomor = (int) cbTujuan.getSelectedIndex();
                switch (nomor) {
                    case 1: {
                        txtTujuan.setText("Bukittinggi");
                    }

                    break;
                    case 2: {
                        txtTujuan.setText("Solok");
                    }

                    break;
                    case 3: {
                        txtTujuan.setText("Batusangkar");
                    }

                    break;
                    case 4: {
                        txtTujuan.setText("Sijunjung");
                    }

                    break;
                    case 5: {
                        txtTujuan.setText("Padang Panjang");
                    }

                    break;
                }

                String tujuan = cbTujuan.getSelectedItem().toString();
                String kelas = "";

                if (rbEkonomi.isSelected()) {
                    kelas = "Ekonomi";
                    txtKelas.setText("Ekonomi");
                } else if (rbExecutive.isSelected()) {
                    kelas = "Executive";
                    txtKelas.setText("Executive");
                } else if (rbSe.isSelected()) {
                    kelas = "Super Executive";
                    txtKelas.setText("Super Executive");
                }

                double harga = 0;
                if (tujuan == "Bukittinggi") {
                    if (kelas == "Ekonomi") {
                        harga = 30000;
                    } else if (kelas == "Executive") {
                        harga = 40000;
                    } else if (kelas == "Super Executive") {
                        harga = 50000;
                    }
                } else if (tujuan == "Batusangkar") {
                    if (kelas == "Ekonomi") {
                        harga = 35000;
                    } else if (kelas == "Executive") {
                        harga = 45000;
                    } else if (kelas == "Super Executive") {
                        harga = 55000;
                    }
                } else if (tujuan == "Solok") {
                    if (kelas == "Ekonomi") {
                        harga = 30000;
                    } else if (kelas == "Executive") {
                        harga = 40000;
                    } else if (kelas == "Super Executive") {
                        harga = 50000;
                    }
                } else if (tujuan == "Sijunjung") {
                    if (kelas == "Ekonomi") {
                        harga = 45000;
                    } else if (kelas == "Executive") {
                        harga = 55000;
                    } else if (kelas == "Super Executive") {
                        harga = 65000;
                    }
                } else if (tujuan == "Padang Panjang") {
                    if (kelas == "Ekonomi") {
                        harga = 25000;
                    } else if (kelas == "Executive") {
                        harga = 35000;
                    } else if (kelas == "Super Executive") {
                        harga = 45000;
                    }
                }
                txtHarga.setText(Double.toString(harga));
                int tiket = Integer.parseInt(txtTiket.getText());
                double total = harga * tiket;
                double pajak = 0.1 * total;
                double totBayar = total + pajak;
                txtTotal.setText(Double.toString(total));
                txtPajak.setText(Double.toString(pajak));
                txtTBayar.setText(Double.toString(totBayar));

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Input harus berupa angka", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtTiket.setText("");
                txtTiket.requestFocus();
                return;
            }

        }

    }//GEN-LAST:event_btnProsesActionPerformed


    private void cbTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTujuanActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_cbTujuanActionPerformed

    private void rbEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEkonomiActionPerformed

    private void rbExecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbExecutiveActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_rbExecutiveActionPerformed

    private void rbSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_rbSeActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        boolean sukses = false;
        try {
            double uang = Double.parseDouble(txtTBayar.getText());
            double bayar = Double.parseDouble(txtPembayaran.getText());
            double kembalian = bayar - uang;
            txtKembalian.setText(Double.toString(kembalian));
            sukses = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtPembayaran.setText("");
            txtPembayaran.requestFocus();
        } finally {
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Pemesanan dan pembayaran tiket telah selesai");
            }

        }
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnekaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnekaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnekaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnekaTravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnekaTravel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cbTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbEkonomi;
    private javax.swing.JRadioButton rbExecutive;
    private javax.swing.JRadioButton rbSe;
    private javax.swing.ButtonGroup rgKelas;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtPembayaran;
    private javax.swing.JTextField txtTBayar;
    private javax.swing.JTextField txtTiket;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables
}
